# ─────────────────────────────────────────────────────────────────────────────
# catalogo.py  —  Catálogo de productos del bot
# ─────────────────────────────────────────────────────────────────────────────

import os
from config import CATALOG_DIR

def foto(ruta):
    # Compatible con Windows (\) y Linux (/) para Railway
    partes = ruta.replace("\\", "/").split("/")
    return os.path.join(CATALOG_DIR, *partes)

T_ADULTO = ["S", "M", "L", "XL", "XXL", "XXXL", "XXXXL"]
T_NINO   = ["16 (5-6a)", "18 (7-8a)", "20 (9-10a)", "22 (11-12a)",
             "24 (13-14a)", "26 (15-16a)", "28 (17-18a)"]

MENU = {

    # ── BETIS 25/26 ──────────────────────────────────────────────────────────
    "betis_2526": {
        "emoji": "🟢",
        "nombre": "Betis 25/26",
        "equipo": "Betis",
        "temporada": "25/26",
        "productos": [
            {
                "id": "BETIS-2526-HOME-A",
                "nombre": "Betis 25/26 Local Manga Corta",
                "nombre_proveedor": "BETIS 25/26 - HOME - SS",
                "precio": 15,
                "foto": foto(r"LA_LIGA\BETIS\2025-26\CAMISETAS\Betis 25-26 home front.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga", "UEL"],
            },
            {
                "id": "BETIS-2526-HOME-A-ML",
                "nombre": "Betis 25/26 Local Manga Larga",
                "nombre_proveedor": "BETIS 25/26 - HOME - LS",
                "precio": 15,
                "foto": foto(r"LA_LIGA\BETIS\2025-26\CAMISETAS\Home Manga larga 25-26 Betis.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "BETIS-2526-AWAY-A",
                "nombre": "Betis 25/26 Visitante Celeste",
                "nombre_proveedor": "BETIS 25/26 - AWAY - CELESTE - SS",
                "precio": 15,
                "foto": foto(r"LA_LIGA\BETIS\2025-26\CAMISETAS\25-26 Betis away.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga", "UEL"],
            },
            {
                "id": "BETIS-2526-THIRD-A",
                "nombre": "Betis 25/26 Tercera Negra/Turquesa",
                "nombre_proveedor": "BETIS 25/26 - THIRD - BLACK/TURQUOISE - SS",
                "precio": 15,
                "foto": foto(r"LA_LIGA\BETIS\2025-26\CAMISETAS\Betis 25-26 third.jpeg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga", "UEL"],
            },
            {
                "id": "BETIS-2526-GK-BLANCA-A",
                "nombre": "Betis 25/26 Portero Blanca",
                "nombre_proveedor": "BETIS 25/26 - GK - WHITE",
                "precio": 15,
                "foto": foto(r"LA_LIGA\BETIS\2025-26\PORTEROS\Betis GK 25-26.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "BETIS-2526-HOME-N",
                "nombre": "Betis 25/26 Local Niño",
                "nombre_proveedor": "BETIS 25/26 - HOME - KIDS - SS",
                "precio": 20,
                "foto": "",
                "tallas": T_NINO,
                "personalizacion": False,
                "publico": "Niño",
                "parche": None,
            },
            {
                "id": "BETIS-2526-AWAY-N",
                "nombre": "Betis 25/26 Visitante Niño",
                "nombre_proveedor": "BETIS 25/26 - AWAY - KIDS - SS",
                "precio": 20,
                "foto": "",
                "tallas": T_NINO,
                "personalizacion": False,
                "publico": "Niño",
                "parche": None,
            },
            {
                "id": "BETIS-2526-THIRD-N",
                "nombre": "Betis 25/26 Tercera Niño",
                "nombre_proveedor": "BETIS 25/26 - THIRD - KIDS - SS",
                "precio": 20,
                "foto": "",
                "tallas": T_NINO,
                "personalizacion": False,
                "publico": "Niño",
                "parche": None,
            },
            {
                "id": "BETIS-2526-ESP-PRIMAVERA",
                "nombre": "Betis 25/26 Fiesta de Primavera",
                "nombre_proveedor": "BETIS 25/26 - SPRING FESTIVAL",
                "precio": 15,
                "foto": foto(r"LA_LIGA\BETIS\2025-26\EDICIONES_ESPECIALES\Betis fiesta primavera.jpeg"),
                "tallas": T_ADULTO,
                "personalizacion": False,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "BETIS-2526-ESP-WOMENDAY",
                "nombre": "Betis 25/26 Women's Day Bética",
                "nombre_proveedor": "BETIS 25/26 - WOMEN'S DAY - BETICA",
                "precio": 15,
                "foto": foto(r"LA_LIGA\BETIS\2025-26\EDICIONES_ESPECIALES\Bestis Women Day.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": False,
                "publico": "Adulto",
                "parche": None,
            },
        ],
    },

    # ── BETIS 26/27 ──────────────────────────────────────────────────────────
    "betis_2627": {
        "emoji": "🟢",
        "nombre": "Betis 26/27",
        "equipo": "Betis",
        "temporada": "26/27",
        "productos": [
            {
                "id": "BETIS-2627-HOME-A",
                "nombre": "Betis 26/27 Local Fan",
                "nombre_proveedor": "BETIS 26/27 - HOME - FAN - SS",
                "precio": 15,
                "foto": foto(r"LA_LIGA\BETIS\2026-27\CAMISETAS\betis 26-27 home version fan front.jpeg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga", "UCL"],
            },
            {
                "id": "BETIS-2627-HOME-PLAYER-A",
                "nombre": "Betis 26/27 Local Player",
                "nombre_proveedor": "BETIS 26/27 - HOME - PLAYER - SS",
                "precio": 17,
                "foto": foto(r"LA_LIGA\BETIS\2026-27\CAMISETAS\betis 26-27 home version player front.jpeg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga", "UCL"],
            },
            {
                "id": "BETIS-2627-HOME-N",
                "nombre": "Betis 26/27 Local Niño",
                "nombre_proveedor": "BETIS 26/27 - HOME - KIDS - SS",
                "precio": 20,
                "foto": foto(r"LA_LIGA\BETIS\2026-27\CAMISETAS\Betis 26-27 home kids.jpeg"),
                "tallas": T_NINO,
                "personalizacion": False,
                "publico": "Niño",
                "parche": None,
            },
            {
                "id": "BETIS-2627-AWAY-A",
                "nombre": "Betis 26/27 Visitante Verde",
                "nombre_proveedor": "BETIS 26/27 - AWAY - GREEN - SS",
                "precio": 15,
                "foto": foto(r"LA_LIGA\BETIS\2026-27\CAMISETAS\Betis 26-27 away front.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga", "UCL"],
            },
            {
                "id": "BETIS-2627-AWAY-N",
                "nombre": "Betis 26/27 Visitante Niño",
                "nombre_proveedor": "BETIS 26/27 - AWAY - KIDS - SS",
                "precio": 20,
                "foto": "",
                "tallas": T_NINO,
                "personalizacion": False,
                "publico": "Niño",
                "parche": None,
                "stock": False,
            },
            {
                "id": "BETIS-2627-THIRD-A",
                "nombre": "Betis 26/27 Tercera Azul/Negra",
                "nombre_proveedor": "BETIS 26/27 - THIRD - BLUE/BLACK - SS",
                "precio": 15,
                "foto": foto(r"LA_LIGA\BETIS\2026-27\CAMISETAS\Betis 26-27 third.jpeg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga", "UCL"],
            },
            {
                "id": "BETIS-2627-THIRD-N",
                "nombre": "Betis 26/27 Tercera Niño",
                "nombre_proveedor": "BETIS 26/27 - THIRD - KIDS - SS",
                "precio": 20,
                "foto": "",
                "tallas": T_NINO,
                "personalizacion": False,
                "publico": "Niño",
                "parche": None,
                "stock": False,
            },
            {
                "id": "BETIS-2627-TRAIN-VERDE-A",
                "nombre": "Betis 26/27 Entrenamiento Verde",
                "nombre_proveedor": "BETIS 26/27 - TRAINING - GREEN",
                "precio": 15,
                "foto": foto(r"LA_LIGA\BETIS\2026-27\ENTRENAMIENTO\Betis 26-27 Train Green.jpeg"),
                "tallas": T_ADULTO,
                "personalizacion": False,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "BETIS-2627-TRAIN-BLANCA-A",
                "nombre": "Betis 26/27 Entrenamiento Blanca",
                "nombre_proveedor": "BETIS 26/27 - TRAINING - WHITE",
                "precio": 15,
                "foto": foto(r"LA_LIGA\BETIS\2026-27\ENTRENAMIENTO\Betis 26-27 Train White.jpeg"),
                "tallas": T_ADULTO,
                "personalizacion": False,
                "publico": "Adulto",
                "parche": None,
            },
        ],
    },

    # ── REAL MADRID 26/27 ─────────────────────────────────────────────────────
    "real_madrid_2627": {
        "emoji": "⚪",
        "nombre": "Real Madrid 26/27",
        "equipo": "Real Madrid",
        "temporada": "26/27",
        "productos": [
            {
                "id": "REALMADRID-2627-HOME-A",
                "nombre": "Real Madrid 26/27 Local Adulto",
                "nombre_proveedor": "REAL MADRID 26/27 - HOME - ADULT",
                "precio": 15,
                "foto": foto(r"LA_LIGA\REAL_MADRID\2026-27\CAMISETAS\real-madrid-26-27-home-adulto.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga", "UCL"],
            },
            {
                "id": "REALMADRID-2627-AWAY-A",
                "nombre": "Real Madrid 26/27 Visitante Adulto",
                "nombre_proveedor": "REAL MADRID 26/27 - AWAY - ADULT",
                "precio": 15,
                "foto": foto(r"LA_LIGA\REAL_MADRID\2026-27\CAMISETAS\real-madrid-26-27-away-adulto.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga", "UCL"],
            },
            {
                "id": "REALMADRID-2627-THIRD-A",
                "nombre": "Real Madrid 26/27 Tercera Adulto",
                "nombre_proveedor": "REAL MADRID 26/27 - THIRD - ADULT",
                "precio": 15,
                "foto": foto(r"LA_LIGA\REAL_MADRID\2026-27\CAMISETAS\real-madrid-26-27-third-adulto.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga", "UCL"],
            },
            {
                "id": "REALMADRID-2627-HOME-N",
                "nombre": "Real Madrid 26/27 Local Niño",
                "nombre_proveedor": "REAL MADRID 26/27 - HOME - KIDS",
                "precio": 20,
                "foto": foto(r"LA_LIGA\REAL_MADRID\2026-27\CAMISETAS\real-madrid-26-27-home-nino.jpg"),
                "tallas": T_NINO,
                "personalizacion": False,
                "publico": "Niño",
                "parche": None,
            },
            {
                "id": "REALMADRID-2627-AWAY-N",
                "nombre": "Real Madrid 26/27 Visitante Niño",
                "nombre_proveedor": "REAL MADRID 26/27 - AWAY - KIDS",
                "precio": 20,
                "foto": foto(r"LA_LIGA\REAL_MADRID\2026-27\CAMISETAS\real-madrid-26-27-away-nino.jpg"),
                "tallas": T_NINO,
                "personalizacion": False,
                "publico": "Niño",
                "parche": None,
            },
            {
                "id": "REALMADRID-2627-THIRD-N",
                "nombre": "Real Madrid 26/27 Tercera Niño",
                "nombre_proveedor": "REAL MADRID 26/27 - THIRD - KIDS",
                "precio": 20,
                "foto": foto(r"LA_LIGA\REAL_MADRID\2026-27\CAMISETAS\real-madrid-26-27-third-nino.jpg"),
                "tallas": T_NINO,
                "personalizacion": False,
                "publico": "Niño",
                "parche": None,
            },
        ],
    },

    # ── BARCELONA 26/27 ───────────────────────────────────────────────────────
    "barcelona_2627": {
        "emoji": "🔵🔴",
        "nombre": "Barcelona 26/27",
        "equipo": "Barcelona",
        "temporada": "26/27",
        "productos": [
            {
                "id": "BARCELONA-2627-HOME-A",
                "nombre": "Barcelona 26/27 Local Adulto",
                "nombre_proveedor": "BARCELONA 26/27 - HOME - ADULT",
                "precio": 15,
                "foto": foto(r"LA_LIGA\BARCELONA\2026-27\CAMISETAS\barcelona-26-27-home-adulto.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga", "UCL"],
            },
            {
                "id": "BARCELONA-2627-AWAY-A",
                "nombre": "Barcelona 26/27 Visitante Adulto",
                "nombre_proveedor": "BARCELONA 26/27 - AWAY - ADULT",
                "precio": 15,
                "foto": foto(r"LA_LIGA\BARCELONA\2026-27\CAMISETAS\barcelona-26-27-away-adulto.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga", "UCL"],
            },
            {
                "id": "BARCELONA-2627-THIRD-A",
                "nombre": "Barcelona 26/27 Tercera Adulto",
                "nombre_proveedor": "BARCELONA 26/27 - THIRD - ADULT",
                "precio": 15,
                "foto": foto(r"LA_LIGA\BARCELONA\2026-27\CAMISETAS\barcelona-26-27-third-adulto.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga", "UCL"],
            },
        ],
    },

    # ── ATLÉTICO DE MADRID 26/27 ──────────────────────────────────────────────
    "atletico_2627": {
        "emoji": "🔴⚪",
        "nombre": "Atlético Madrid 26/27",
        "equipo": "Atlético de Madrid",
        "temporada": "26/27",
        "productos": [
            {
                "id": "ATLETICO-2627-HOME-A",
                "nombre": "Atlético Madrid 26/27 Local Adulto",
                "nombre_proveedor": "ATLETICO MADRID 26/27 - HOME - ADULT",
                "precio": 15,
                "foto": foto(r"LA_LIGA\ATLETICO_MADRID\2026-27\CAMISETAS\atletico-madrid-26-27-home-adulto.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga", "UCL"],
            },
            {
                "id": "ATLETICO-2627-AWAY-A",
                "nombre": "Atlético Madrid 26/27 Visitante Adulto",
                "nombre_proveedor": "ATLETICO MADRID 26/27 - AWAY - ADULT",
                "precio": 15,
                "foto": foto(r"LA_LIGA\ATLETICO_MADRID\2026-27\CAMISETAS\atletico-madrid-26-27-away-adulto.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga", "UCL"],
            },
        ],
    },

    # ── SEVILLA 26/27 ─────────────────────────────────────────────────────────
    "sevilla_2627": {
        "emoji": "🔴",
        "nombre": "Sevilla 26/27",
        "equipo": "Sevilla FC",
        "temporada": "26/27",
        "productos": [
            {
                "id": "SEVILLA-2627-HOME-A",
                "nombre": "Sevilla 26/27 Local Blanca Adulto",
                "nombre_proveedor": "SEVILLA 26/27 - HOME - WHITE - ADULT",
                "precio": 15,
                "foto": foto(r"LA_LIGA\SEVILLA\2026-27\CAMISETAS\Sevilla 26-27 home.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "SEVILLA-2627-AWAY-A",
                "nombre": "Sevilla 26/27 Visitante Roja Adulto",
                "nombre_proveedor": "SEVILLA 26/27 - AWAY - RED - ADULT",
                "precio": 15,
                "foto": foto(r"LA_LIGA\SEVILLA\2026-27\CAMISETAS\Sevilla 26-27 away.png"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "SEVILLA-2627-THIRD-A",
                "nombre": "Sevilla 26/27 Tercera Negra Adulto",
                "nombre_proveedor": "SEVILLA 26/27 - THIRD - BLACK - ADULT",
                "precio": 15,
                "foto": foto(r"LA_LIGA\SEVILLA\2026-27\CAMISETAS\Sevilla 26-27 third.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "SEVILLA-2627-HOME-N",
                "nombre": "Sevilla 26/27 Local Blanca Niño",
                "nombre_proveedor": "SEVILLA 26/27 - HOME - WHITE - KIDS",
                "precio": 20,
                "foto": foto(r"LA_LIGA\SEVILLA\2026-27\CAMISETAS\Sevilla Kids 26-27 home.jpeg"),
                "tallas": T_NINO,
                "personalizacion": False,
                "publico": "Niño",
                "parche": None,
            },
            {
                "id": "SEVILLA-2627-AWAY-N",
                "nombre": "Sevilla 26/27 Visitante Roja Niño",
                "nombre_proveedor": "SEVILLA 26/27 - AWAY - RED - KIDS",
                "precio": 20,
                "foto": foto(r"LA_LIGA\SEVILLA\2026-27\CAMISETAS\Sevilla Kids 26-27 away.jpeg"),
                "tallas": T_NINO,
                "personalizacion": False,
                "publico": "Niño",
                "parche": None,
            },
            {
                "id": "SEVILLA-2627-THIRD-N",
                "nombre": "Sevilla 26/27 Tercera Negra Niño",
                "nombre_proveedor": "SEVILLA 26/27 - THIRD - BLACK - KIDS",
                "precio": 20,
                "foto": foto(r"LA_LIGA\SEVILLA\2026-27\CAMISETAS\Sevilla kids 26-27 third.jpeg"),
                "tallas": T_NINO,
                "personalizacion": False,
                "publico": "Niño",
                "parche": None,
            },
        ],
    },

    # ── ATHLETIC BILBAO 26/27 ─────────────────────────────────────────────────
    "athletic_2627": {
        "emoji": "🔴⚪",
        "nombre": "Athletic Bilbao 26/27",
        "equipo": "Athletic Bilbao",
        "temporada": "26/27",
        "productos": [
            {
                "id": "ATHLETIC-2627-HOME-A",
                "nombre": "Athletic Bilbao 26/27 Local Adulto",
                "nombre_proveedor": "ATHLETIC BILBAO 26/27 - HOME - ADULT",
                "precio": 15,
                "foto": foto(r"LA_LIGA\ATHLETIC_BILBAO\2026-27\CAMISETAS\athletic-bilbao-26-27-home-adulto.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga"],
            },
        ],
    },

    # ── VALENCIA 26/27 ────────────────────────────────────────────────────────
    "valencia_2627": {
        "emoji": "🦇",
        "nombre": "Valencia 26/27",
        "equipo": "Valencia CF",
        "temporada": "26/27",
        "productos": [
            {
                "id": "VALENCIA-2627-HOME-A",
                "nombre": "Valencia 26/27 Local Adulto",
                "nombre_proveedor": "VALENCIA 26/27 - HOME - ADULT",
                "precio": 15,
                "foto": foto(r"LA_LIGA\VALENCIA\2026-27\CAMISETAS\valencia-26-27-home-adulto.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga"],
            },
            {
                "id": "VALENCIA-2627-AWAY-A",
                "nombre": "Valencia 26/27 Visitante Adulto",
                "nombre_proveedor": "VALENCIA 26/27 - AWAY - ADULT",
                "precio": 15,
                "foto": foto(r"LA_LIGA\VALENCIA\2026-27\CAMISETAS\valencia-26-27-away-adulto.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga"],
            },
        ],
    },

    # ── OSASUNA 26/27 ─────────────────────────────────────────────────────────
    "osasuna_2627": {
        "emoji": "🔴",
        "nombre": "Osasuna 26/27",
        "equipo": "Osasuna",
        "temporada": "26/27",
        "productos": [
            {
                "id": "OSASUNA-2627-HOME-A",
                "nombre": "Osasuna 26/27 Local Adulto",
                "nombre_proveedor": "OSASUNA 26/27 - HOME - ADULT",
                "precio": 15,
                "foto": foto(r"LA_LIGA\OSASUNA\2026-27\CAMISETAS\osasuna-26-27-home-adulto.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga"],
            },
        ],
    },

    # ── RAYO VALLECANO 26/27 ──────────────────────────────────────────────────
    "rayo_2627": {
        "emoji": "⚡",
        "nombre": "Rayo Vallecano 26/27",
        "equipo": "Rayo Vallecano",
        "temporada": "26/27",
        "productos": [
            {
                "id": "RAYO-2627-HOME-A",
                "nombre": "Rayo Vallecano 26/27 Local Adulto",
                "nombre_proveedor": "RAYO VALLECANO 26/27 - HOME - ADULT",
                "precio": 15,
                "foto": foto(r"LA_LIGA\RAYO_VALLECANO\2026-27\CAMISETAS\rayo-vallecano-26-27-home-adulto.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga"],
            },
        ],
    },

    # ── GIRONA 26/27 ──────────────────────────────────────────────────────────
    "girona_2627": {
        "emoji": "🔴⚪",
        "nombre": "Girona 26/27",
        "equipo": "Girona FC",
        "temporada": "26/27",
        "productos": [
            {
                "id": "GIRONA-2627-AWAY-A",
                "nombre": "Girona 26/27 Visitante Adulto",
                "nombre_proveedor": "GIRONA 26/27 - AWAY - ADULT",
                "precio": 15,
                "foto": foto(r"LA_LIGA\GIRONA\2026-27\CAMISETAS\girona-26-27-away-adulto.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga"],
            },
        ],
    },

    # ── ESPANYOL 26/27 ────────────────────────────────────────────────────────
    "espanyol_2627": {
        "emoji": "🔵⚪",
        "nombre": "Espanyol 26/27",
        "equipo": "RCD Espanyol",
        "temporada": "26/27",
        "productos": [
            {
                "id": "ESPANYOL-2627-HOME-A",
                "nombre": "Espanyol 26/27 Local Adulto",
                "nombre_proveedor": "ESPANYOL 26/27 - HOME - ADULT",
                "precio": 15,
                "foto": foto(r"LA_LIGA\ESPANYOL\2026-27\CAMISETAS\espanyol-26-27-home-adulto.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": ["La Liga"],
            },
        ],
    },

    # ── ESPAÑA ★★ ─────────────────────────────────────────────────────────────
    "espana": {
        "emoji": "🇪🇸",
        "nombre": "España ★★",
        "equipo": "Selección Española",
        "temporada": "2026",
        "productos": [
            {
                "id": "ESPANA-WC26-HOME-PLAYER-A",
                "nombre": "España Local Player ★★",
                "nombre_proveedor": "SPAIN - HOME - PLAYER - 2 STARS",
                "precio": 20,
                "foto": foto(r"SELECCIONES\ESPANA\Spain home 2stars version player.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "ESPANA-WC26-AWAY-PLAYER-A",
                "nombre": "España Visitante Player ★★",
                "nombre_proveedor": "SPAIN - AWAY - PLAYER - 2 STARS",
                "precio": 20,
                "foto": foto(r"SELECCIONES\ESPANA\Spain Away Version Player 2 stars.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "ESPANA-WC26-HOME-FAN-A",
                "nombre": "España Local Fan ★★",
                "nombre_proveedor": "SPAIN - HOME - FAN - 2 STARS",
                "precio": 15,
                "foto": foto(r"SELECCIONES\ESPANA\Spain Version Fan 2stars home.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "ESPANA-WC26-AWAY-FAN-A",
                "nombre": "España Visitante Fan ★★",
                "nombre_proveedor": "SPAIN - AWAY - FAN - 2 STARS",
                "precio": 15,
                "foto": foto(r"SELECCIONES\ESPANA\Spain Away Fan Version 2stars.jpeg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "ESPANA-WC26-HOME-N",
                "nombre": "España Local Niño ★★",
                "nombre_proveedor": "SPAIN - HOME - KIDS - 2 STARS",
                "precio": 20,
                "foto": foto(r"SELECCIONES\ESPANA\Spain Home KIds 2stars.jpg"),
                "tallas": T_NINO,
                "personalizacion": False,
                "publico": "Niño",
                "parche": None,
            },
            {
                "id": "ESPANA-WC26-AWAY-N",
                "nombre": "España Visitante Niño ★★",
                "nombre_proveedor": "SPAIN - AWAY - KIDS - 2 STARS",
                "precio": 20,
                "foto": foto(r"SELECCIONES\ESPANA\Spain KIDS away 2stars.png"),
                "tallas": T_NINO,
                "personalizacion": False,
                "publico": "Niño",
                "parche": None,
            },
        ],
    },

    # ── NORUEGA ───────────────────────────────────────────────────────────────
    "noruega": {
        "emoji": "🇳🇴",
        "nombre": "Noruega",
        "equipo": "Selección Noruega",
        "temporada": "2026",
        "productos": [
            {
                "id": "NORWAY-HOME-PLAYER-A",
                "nombre": "Noruega Local Player",
                "nombre_proveedor": "NORWAY - HOME - PLAYER - ADULT - SS",
                "precio": 20,
                "foto": foto(r"SELECCIONES\NORUEGA\2026 Noruega Home Version Player.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "NORWAY-HOME-A",
                "nombre": "Noruega Local Fan",
                "nombre_proveedor": "NORWAY - HOME - FAN - ADULT - SS",
                "precio": 15,
                "foto": foto(r"SELECCIONES\NORUEGA\2026 Noruega Home Version Fan.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "NORWAY-AWAY-A",
                "nombre": "Noruega Visitante Adulto",
                "nombre_proveedor": "NORWAY - AWAY - ADULT - SS",
                "precio": 15,
                "foto": "",
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "NORWAY-HOME-N",
                "nombre": "Noruega Local Niño",
                "nombre_proveedor": "NORWAY - HOME - KIDS - SS",
                "precio": 20,
                "foto": foto(r"SELECCIONES\NORUEGA\2026 Noruega Home KIDS.jpg"),
                "tallas": T_NINO,
                "personalizacion": False,
                "publico": "Niño",
                "parche": None,
            },
            {
                "id": "NORWAY-AWAY-N",
                "nombre": "Noruega Visitante Niño",
                "nombre_proveedor": "NORWAY - AWAY - KIDS - SS",
                "precio": 20,
                "foto": "",
                "tallas": T_NINO,
                "personalizacion": False,
                "publico": "Niño",
                "parche": None,
            },
        ],
    },

    # ── PORTUGAL ──────────────────────────────────────────────────────────────
    "portugal": {
        "emoji": "🇵🇹",
        "nombre": "Portugal",
        "equipo": "Selección Portugal",
        "temporada": "2026",
        "productos": [
            {
                "id": "PORTUGAL-HOME-PLAYER-A",
                "nombre": "Portugal Local Player",
                "nombre_proveedor": "PORTUGAL - HOME - PLAYER - ADULT - SS",
                "precio": 20,
                "foto": foto(r"SELECCIONES\PORTUGAL\2026 Portugal Home Version Player.png"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "PORTUGAL-HOME-A",
                "nombre": "Portugal Local Fan",
                "nombre_proveedor": "PORTUGAL - HOME - FAN - ADULT - SS",
                "precio": 15,
                "foto": foto(r"SELECCIONES\PORTUGAL\2026 Portugal Home Version Fan.png"),
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "PORTUGAL-AWAY-A",
                "nombre": "Portugal Visitante Adulto",
                "nombre_proveedor": "PORTUGAL - AWAY - ADULT - SS",
                "precio": 15,
                "foto": "",
                "tallas": T_ADULTO,
                "personalizacion": True,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "PORTUGAL-HOME-N",
                "nombre": "Portugal Local Niño",
                "nombre_proveedor": "PORTUGAL - HOME - KIDS - SS",
                "precio": 20,
                "foto": foto(r"SELECCIONES\PORTUGAL\2026 Portugal Home KIDS.jpg"),
                "tallas": T_NINO,
                "personalizacion": False,
                "publico": "Niño",
                "parche": None,
            },
            {
                "id": "PORTUGAL-AWAY-N",
                "nombre": "Portugal Visitante Niño",
                "nombre_proveedor": "PORTUGAL - AWAY - KIDS - SS",
                "precio": 20,
                "foto": "",
                "tallas": T_NINO,
                "personalizacion": False,
                "publico": "Niño",
                "parche": None,
            },
        ],
    },

    # ── RETROS ────────────────────────────────────────────────────────────────
    "retros": {
        "emoji": "🏆",
        "nombre": "Retros",
        "equipo": "Betis",
        "temporada": "Retro",
        "productos": [
            {
                "id": "RETRO-BETIS-9697-HOME-ML",
                "nombre": "Betis Retro 96/97 Manga Larga",
                "nombre_proveedor": "BETIS RETRO 96/97 - HOME - LS",
                "precio": 23,
                "foto": foto(r"LA_LIGA\BETIS\RETROS\Manga larga 96-97 Betis.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": False,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "RETRO-BETIS-9697-AWAY",
                "nombre": "Betis Retro 96/97 Visitante",
                "nombre_proveedor": "BETIS RETRO 96/97 - AWAY",
                "precio": 23,
                "foto": foto(r"LA_LIGA\BETIS\RETROS\retro away 96-97 Betis.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": False,
                "publico": "Adulto",
                "parche": None,
            },
        ],
    },

    # ── CHÁNDALS Y CORTAVIENTOS ───────────────────────────────────────────────
    "chandals": {
        "emoji": "🧥",
        "nombre": "Chándals y Cortavientos",
        "equipo": "Betis",
        "temporada": "Varios",
        "productos": [
            {
                "id": "BETIS-2627-CORTAVIENTO-PINK",
                "nombre": "Betis 26/27 Cortaviento Rosa",
                "nombre_proveedor": "BETIS 26/27 - WINDBREAKER - PINK",
                "precio": 30,
                "foto": foto(r"LA_LIGA\BETIS\CHANDALS\Betis Cortaviendo 26-27 Pink.jpeg"),
                "tallas": T_ADULTO,
                "personalizacion": False,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "BETIS-2627-CORTAVIENTO-WHITE",
                "nombre": "Betis 26/27 Cortaviento Blanco",
                "nombre_proveedor": "BETIS 26/27 - WINDBREAKER - WHITE",
                "precio": 30,
                "foto": foto(r"LA_LIGA\BETIS\CHANDALS\Betis Cortaviendo 26-27 White.jpeg"),
                "tallas": T_ADULTO,
                "personalizacion": False,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "BETIS-2627-CORTAVIENTO-GREEN",
                "nombre": "Betis 26/27 Cortaviento Verde",
                "nombre_proveedor": "BETIS 26/27 - WINDBREAKER - GREEN",
                "precio": 30,
                "foto": foto(r"LA_LIGA\BETIS\CHANDALS\Betis Cortaviento 26-27 Green.jpeg"),
                "tallas": T_ADULTO,
                "personalizacion": False,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "BETIS-2526-CORTAVIENTO-1",
                "nombre": "Betis 25/26 Cortaviento Modelo 1",
                "nombre_proveedor": "BETIS 25/26 - WINDBREAKER - MODEL 1",
                "precio": 30,
                "foto": foto(r"LA_LIGA\BETIS\CHANDALS\Betis Cortaviendo 25-26.jpg"),
                "tallas": T_ADULTO,
                "personalizacion": False,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "BETIS-2526-CORTAVIENTO-2",
                "nombre": "Betis 25/26 Cortaviento Modelo 2",
                "nombre_proveedor": "BETIS 25/26 - WINDBREAKER - MODEL 2",
                "precio": 30,
                "foto": foto(r"LA_LIGA\BETIS\CHANDALS\Betis  Chandal cortaviendo 25-26.jpeg"),
                "tallas": T_ADULTO,
                "personalizacion": False,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "BETIS-RETRO-CHANDAL-1",
                "nombre": "Betis Retro Chándal Modelo 1",
                "nombre_proveedor": "BETIS RETRO - TRACKSUIT - MODEL 1",
                "precio": 50,
                "foto": foto(r"LA_LIGA\BETIS\CHANDALS\Chandal Betis Retro 1.jpeg"),
                "tallas": T_ADULTO,
                "personalizacion": False,
                "publico": "Adulto",
                "parche": None,
            },
            {
                "id": "BETIS-RETRO-CHANDAL-2",
                "nombre": "Betis Retro Chándal Modelo 2",
                "nombre_proveedor": "BETIS RETRO - TRACKSUIT - MODEL 2",
                "precio": 50,
                "foto": foto(r"LA_LIGA\BETIS\CHANDALS\Chandal Betis retro 2.jpeg"),
                "tallas": T_ADULTO,
                "personalizacion": False,
                "publico": "Adulto",
                "parche": None,
            },
        ],
    },
}

# ── Índice plano por ID para búsquedas rápidas ────────────────────────────────
PRODUCTOS_POR_ID = {}
for seccion in MENU.values():
    for p in seccion["productos"]:
        PRODUCTOS_POR_ID[p["id"]] = p
